---
- name: Enable Elasticsearch service
  become: true
  service:
    name: elasticsearch
    state: started
    enabled: yes
- name: Configure Elasticsearch
  become: true
  template:
    src: elasticsearch.yml.j2
    mode: 0644
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart Elasticsearch
