---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Get stats of the FS object
    wait_for:
      path: /var/log/elasticsearch/elasticsearch.log
      state: present
      timeout: 60
  - name: Check if port 9200 is listening
    wait_for:
      port: 9200
      timeout: 60
      msg: "Timeout waiting for 9200 to respond"
